<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting=array (
  'site_name' => 'DiliCMS',
  'site_domain' => 'http://www.dilicms.com/',
  'site_logo' => 'images/logo.gif',
  'site_icp' => '',
  'site_terms' => '',
  'site_stats' => '',
  'site_footer' => '',
  'site_status' => '1',
  'site_close_reason' => '网站维护升级中......',
  'site_keyword' => 'DiliCMS,CodeIgniter,DiliCMS最新版',
  'site_description' => 'DiliCMS 基于CodeIgniter的开源免费 专业面向开发者的CMS系统',
  'site_theme' => 'default',
  'attachment_url' => NULL,
  'attachment_dir' => 'attachments',
  'attachment_type' => '*.jpg;*.gif;*.png;*.doc',
  'attachment_maxupload' => '2097152',
  'thumbs_preferences' => '[]',
);